l = {}
name=input("name")
lang=input("language")
l.update({name:lang})
name=input("name")
lang=input("language")
l.update({name:lang})
name=input("name")
lang=input("language")
l.update({name:lang})
name=input("name")
lang=input("language")
l.update({name:lang})
name=input("name")
lang=input("language")
l.update({name :lang})
print(l)
