m = []
m1=int(input("mark of 1"))
m.append(m1)
m2=int(input("markof 2"))
m.append(m2)
m3=int(input("mark of 3"))
m.append(m3)
m4=int(input("mark of4"))
m.append(m4)
m5=int(input("mark of 5"))
m.append(m5)
m6=int(input("mark of 6"))
m.append(m6)
m.sort()
print(m)