f =[]
f1 = input("fruit")
f.append(f1)
f2 = input("fruit")
f.append(f2)
f3 = input("fruit")
f.append(f3)
f4 = input("fruit")
f.append(f4)
f5 = input("fruit")
f.append(f5)
f6 = input("fruit")
f.append(f6)
print(f)