u = set()
d=int(input("enter the numbers"))
u.add(d)
d=int(input("enter the numbers"))
u.add(d)
d=int(input("enter the numbers"))
u.add(d)
d=int(input("enter the numbers"))
u.add(d)
d=int(input("enter the numbers"))
u.add(d)
d=int(input("enter the numbers"))
u.add(d)
d=int(input("enter the numbers"))
u.add(d)
print(u)